name: advent_song
description: A song lyric app built with Flutter.

# Version of your application
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Flutter material design package
  cupertino_icons: ^1.0.2

  # Package for saving user preferences locally
  shared_preferences: ^2.0.15

  # Logger package for structured logging instead of print statements
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint rules for flutter projects
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets used in the application
  assets:
    - assets/lpmi.json
    - assets/srd.json
    - assets/iban.json
    - assets/pandak.json
    - assets/header_image.png  # Ensure the path is correct.
