name: advent_song
description: A song lyrics app built with Flutter.

publish_to: 'none' # Prevents publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0' # Ensure the SDK version matches your Flutter setup.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  intl: ^0.18.0 # For date formatting in your app.
  logger: ^1.1.0 # For logging purposes.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0 # Add this line if not already present

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png" # Ensure this is the correct path to your icon
  adaptive_icon_background: "#FFFFFF" # Optional: Background color for adaptive icons
  adaptive_icon_foreground: "assets/icon/icon.png" # Use the same icon for the foreground

flutter:
  uses-material-design: true # Enables the use of Material Icons in your app.

  assets:
    - assets/header_image.png
    - assets/lpmi.json
    - assets/srd.json
    - assets/iban.json
    - assets/pandak.json
    - assets/icon/icon.png # Ensure the icon is in the correct location
