// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzQ0JJvdt9mVM23ejgcJi95_8r9BwXmYU',
    appId: '1:1043393288929:web:645ed4fb559bb6055cf5a0',
    messagingSenderId: '1043393288929',
    projectId: 'advent-song',
    authDomain: 'advent-song.firebaseapp.com',
    databaseURL:
        'https://advent-song-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'advent-song.firebasestorage.app',
    measurementId: 'G-2JKH0C9SXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyAzQ0JJvdt9mVM23ejgcJi95_8r9BwXmYU', // Using web API key for now
    appId:
        '1:1043393288929:android:YOUR_ANDROID_APP_ID', // Replace with Android app ID
    messagingSenderId: '1043393288929',
    projectId: 'advent-song',
    databaseURL:
        'https://advent-song-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'advent-song.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyAzQ0JJvdt9mVM23ejgcJi95_8r9BwXmYU', // Using web API key for now
    appId: '1:1043393288929:ios:YOUR_IOS_APP_ID', // Replace with iOS app ID
    messagingSenderId: '1043393288929',
    projectId: 'advent-song',
    databaseURL:
        'https://advent-song-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'advent-song.firebasestorage.app',
    iosBundleId: 'com.example.adventSong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:
        'AIzaSyAzQ0JJvdt9mVM23ejgcJi95_8r9BwXmYU', // Using web API key for now
    appId: '1:1043393288929:ios:YOUR_MACOS_APP_ID', // Replace with macOS app ID
    messagingSenderId: '1043393288929',
    projectId: 'advent-song',
    databaseURL:
        'https://advent-song-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'advent-song.firebasestorage.app',
    iosBundleId: 'com.example.adventSong',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzQ0JJvdt9mVM23ejgcJi95_8r9BwXmYU',
    appId: '1:1043393288929:web:645ed4fb559bb6055cf5a0', // Windows uses web app
    messagingSenderId: '1043393288929',
    projectId: 'advent-song',
    authDomain: 'advent-song.firebaseapp.com',
    databaseURL:
        'https://advent-song-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'advent-song.firebasestorage.app',
    measurementId: 'G-2JKH0C9SXH',
  );
}
