// main.dart - UPDATED WITH FIREBASE INITIALIZATION
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'services/firebase_service.dart';
import 'theme_notifier.dart';
import 'landing_page.dart';
import 'admin_login_page_firebase.dart'; // Updated admin login
import 'admin_dashboard_firebase.dart'; // Updated admin dashboard

void main() async {
  // Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();

  try {
    // Initialize Firebase
    print('🔥 Initializing Firebase...');
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    print('✅ Firebase initialized successfully');

    // Initialize Firebase service (offline persistence, etc.)
    await FirebaseService.initialize();
    print('✅ Firebase service initialized');
  } catch (e) {
    print('❌ Firebase initialization failed: $e');
    // App can still run with limited functionality
  }

  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  late ThemeNotifier _themeNotifier;

  @override
  void initState() {
    super.initState();
    _themeNotifier = ThemeNotifier();
    _themeNotifier.initialize();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _themeNotifier,
      builder: (context, child) {
        if (!_themeNotifier.isInitialized) {
          return MaterialApp(
            home: Scaffold(
              body: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    CircularProgressIndicator(),
                    SizedBox(height: 16),
                    Text('Loading app...'),
                  ],
                ),
              ),
            ),
            debugShowCheckedModeBanner: false,
          );
        }

        final lightColorScheme = _themeNotifier.buildColorScheme(false);
        final darkColorScheme = _themeNotifier.buildColorScheme(true);

        // Create a unique key for each theme combination
        final themeKey =
            '${_themeNotifier.selectedColorTheme}_${_themeNotifier.isDarkMode}_${DateTime.now().millisecondsSinceEpoch}';

        return MaterialApp(
          key: ValueKey(themeKey),
          title: 'Lagu Advent',
          theme: ThemeData(
            useMaterial3: true,
            fontFamily: 'SF Pro Display',
            colorScheme: lightColorScheme,
            appBarTheme: AppBarTheme(
              backgroundColor: lightColorScheme.surface,
              foregroundColor: lightColorScheme.onSurface,
              elevation: 0,
            ),
            cardTheme: CardTheme(
              elevation: 2,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
            filledButtonTheme: FilledButtonThemeData(
              style: FilledButton.styleFrom(
                backgroundColor: lightColorScheme.primary,
                foregroundColor: lightColorScheme.onPrimary,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
            ),
            outlinedButtonTheme: OutlinedButtonThemeData(
              style: OutlinedButton.styleFrom(
                foregroundColor: lightColorScheme.primary,
                side: BorderSide(color: lightColorScheme.primary),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
            ),
          ),
          darkTheme: ThemeData(
            useMaterial3: true,
            fontFamily: 'SF Pro Display',
            colorScheme: darkColorScheme,
            appBarTheme: AppBarTheme(
              backgroundColor: darkColorScheme.surface,
              foregroundColor: darkColorScheme.onSurface,
              elevation: 0,
            ),
            cardTheme: CardTheme(
              elevation: 8,
              shadowColor: Colors.black.withOpacity(0.5),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
            filledButtonTheme: FilledButtonThemeData(
              style: FilledButton.styleFrom(
                backgroundColor: darkColorScheme.primary,
                foregroundColor: darkColorScheme.onPrimary,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
            ),
            outlinedButtonTheme: OutlinedButtonThemeData(
              style: OutlinedButton.styleFrom(
                foregroundColor: darkColorScheme.primary,
                side: BorderSide(color: darkColorScheme.primary),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
            ),
          ),
          themeMode:
              _themeNotifier.isDarkMode ? ThemeMode.dark : ThemeMode.light,

          // 🔥 UPDATED ROUTES FOR FIREBASE
          initialRoute: '/',
          routes: {
            '/': (context) => LandingPage(
                  key: ValueKey(themeKey),
                  themeNotifier: _themeNotifier,
                ),
            '/admin-login': (context) => const AdminLoginPageFirebase(),
            '/admin-dashboard': (context) => const AdminDashboardFirebase(),
          },

          debugShowCheckedModeBanner: false,
        );
      },
    );
  }
}
